### ISSUE TITLE
Add support for short positions in lots

### ISSUE THREAD

**Issue by pichalite** [achannarasappa/ticker#127]
**Problem Statement**
Add support for shorted positions

**Proposed Solution**
Short position will be identified by negative quantity in the lots. Cost of the shot position will be current price * quantity (positive). Value will be unit cost * quantity (positive).

**Comment by achannarasappa** [comment]
Thanks for the suggestion!

Do you know if this is available on Yahoo Finance? Would you be able to provide an example if so?

**Comment by pichalite** [comment]
@achannarasappa Don't think there is anything specific you need to get from Yahoo Finance. It's got to do with how you calculate the position values. When you short a stock, you start the position by selling the stock.

When you buy stock, the cost for the position would be quantity * unit_cost and current value would be quantity * current_price.

When you short a stock, the cost for the position would be quantity * current_price and value will be quantity * unit_cost specified in the lot. In this case, value will be constant but cost will keep changing.

**Comment by arctica** [comment]
@achannarasappa hi, would you mind re-opening this feature request issue please? I'd be interested in such a feature. As mentioned, you don't need anything from the data feeds for short positions. You just add a negative amount as your position and instead of showing a loss it would show a gain and vice versa. Pretty much just multiply by -1 to get the result. In fact it seems the arrow already seems to be pointing in the right direction, just the color is wrong. Note the attached screenshot where the arrow points up (gain) but the color is red (loss).

![Screen Shot 2022-08-23 at 20 11 16](https://user-images.githubusercontent.com/870630/186232990-4d9b90bd-5015-490c-be03-9708090f6e64.png)
.
