### ISSUE TITLE
Crypto issure - open and close prices are the same

### ISSUE THREAD

**Issue by brolal** [achannarasappa/ticker#226]
**Describe the bug**
Prev. Close and Open are the same for crypto

**To Reproduce**
config file:
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
currency-summary-only: false
watchlist:
  - FIL.X
  - ETC.X
  - BTC.X
  - LTC.X
  - ETH.X
  - XMR.X
  - ADA.X
  - FSR
groups:
  - name: crypto
    watchlist:
      - SHIB-USD
      - DOGE-USD
colors:
  text: "#f49118"
  text-light: "#0087ff"
  text-label: "#A9A9A9"
  text-line: "#00ffff"
  text-tag: "#AFEEEE"
  background-tag: "#696969"

**Expected behavior**
the open and close should be diffrent

**Screenshots**
![Screenshot from 2022-06-25 01-51-36](https://user-images.githubusercontent.com/82910708/175720407-7dc591c8-5f1c-4759-acf5-8d0b3f72f47e.png)

**Environment (please complete the following information):**
 - OS: [Linux]
 - Terminal: [ fedora teminal]
 - Terminal Version: [ fedora 35]

**Additional context**
When adding stocks, it works fine

**Comment by achannarasappa** [comment]
Thanks for calling this issue out - these values are the same because crypto markets do not close and thus do not have an Open price. Even that Prev. Close field is a misnomer since the market never closes.

I've seen the Prev. Close property set to the value of the crypto asset 24 hours ago in other applications that show market data for crypto assets so I've done the same in ticker. I'm open to ideas or suggestions on a clearer way to communicate that property.

For the Open price, I've made a change in the latest release that hides this property for assets that do not have an open price such as crypto assets for clarity.
