### ISSUE TITLE
Session cookie missing for response with Coingecko assets

### ISSUE THREAD

**Issue by rappie** [achannarasappa/ticker#257]
**Describe the bug**
When trying to show `SOLANA.CG` I get the error: `Session cookie missing for response`

**To Reproduce**
1. Run `ticker -w SOLANA.CG`
2. I get the error (see screenshot)

**Expected behavior**
No error :slightly_smiling_face: 

**Screenshots**
![image](https://github.com/achannarasappa/ticker/assets/1430820/3a723729-a746-47fc-9da1-bae9cb3405ca)

**Environment (please complete the following information):**
 - OS: Manjaro Linux (arch based)
 - Terminal: Kitty
 - ticker Version: 4.5.14

**Comment by achannarasappa** [comment]
Is this still occurring? I was able run the example command without issue just now. It is possible that it was a transient issue with the Yahoo API.

If the issue is still occurring, would you mind sharing your country? Yahoo's API behaves different in different region.

For context: although you were attempting to watch a non-Yahoo based asset, ticker still relies on Yahoo's API for currency conversion data and hence makes an authentication call to Yahoo's API on startup. A possible improvement would be to remove the call to Yahoo's API if there were no equities and no currency conversion.

**Comment by eject7455** [comment]
Happens to me as well (USA)

**Comment by igorshirinkin** [comment]
Same issue (Russia)
