### ISSUE TITLE
Total for lots?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#4]
May be displaying totals for lots (in the status line?) could be worth considering? :)

Otherwise, seems like a great app, already using it.

**Comment by achannarasappa** [comment]
Thanks for the suggestion! This was a feature I considering but wanted to wait until I knew there was interest for it and now I know there is :)

**Comment by brandenc40** [comment]
+1 would love to have this. overall holding gain/loss is the one thing I'm missing

**Comment by cpjolicoeur** [comment]
Same here.  I've already forked and added this to my own fork but it appears that @wbbradley has already submitted a PR for the feature, so I'll not open one for mine.

For me, having the option (or even the default) to see the total gain/loss on existing lots is more valuable/useful information than seeing just the daily gain/loss.

**Comment by for-coursera** [comment]
> By default it would show your daily gain/loss like it does now, or if the config option is set, it would instead show you your total gain/loss.

You mean totals for every stock separately? You bought your lot for 10, after 5 weeks it's 15, and you want to be able to see this total, 5, instead of a daily change? Am I correct?

I think, it would be great to have both totals, a total gain/loss for a particular stock, as you are suggesting, and a total for the whole portfolio, as it was originally suggested by @097115 .

**Comment by cpjolicoeur** [comment]
@for-coursera Yes, I'm suggesting an alternative to the current info that ticker displays for aggregated lots.  Currently the aggregated lots display column shows your daily change and daily change %.  I'm suggesting (as I have done in my fork) that, this could be changed to show your total change and total change % instead.

So instead of seeing that my lots gained me $5 today and went up 1.2%, I would see that (since I purchased based no my lot's cost basis) in total I'm up $45.23 dollars and 14.3% (those are just example numbers).

For me, it's more useful to see the total gain/loss on my lots than daily.  Especially since your daily change % on your lots is going to always be the same daily change % of the stock as a whole (unless you purchased the lot mid-day, but ticker currently doesnt support tracking lot acquisition date).

I do agree with you and think that show total gain/loss for a whole portfolio is also a great addition and would fit nicely into the UI.  I was merely speaking to the total changes on a per stock/lot basis.

**Comment by achannarasappa** [comment]
Thanks for your input everyone. I've implemented the show totals for all positions features in [v2.2.0](https://github.com/achannarasappa/ticker/releases/tag/v2.2.0).

Looks like there's some discussion around other types of totals - I'd suggesting opening a new issue to track that if that's a distinct request from this.
