### ISSUE TITLE
Total change instead of daily change

### ISSUE THREAD

**Issue by trapatsas** [achannarasappa/ticker#57]
Can we have the total change of positions instead of the daily one? I believe it's much more useful.

![daily_position_change](https://user-images.githubusercontent.com/4463408/106919527-e7258480-6712-11eb-8c4e-c962506b104e.png)

**Comment by for-coursera** [comment]
Second that. And also pinging @cpjolicoeur, he had some insightful input on this topic here https://github.com/achannarasappa/ticker/issues/4#issuecomment-772603697

**Comment by cpjolicoeur** [comment]
Yes, I've already implemented this in my fork.  I just need to add a couple test cases to the test suite for it and I'll open a Pull Request here when I do.

**Comment by cpjolicoeur** [comment]
@trapatsas @for-coursera feel free to use my fork if you want until then.  You can see[ the relevant commit here](https://github.com/cpjolicoeur/ticker/commit/d82a8536ad561948c8924e69bca60c6080c7a14d)

**Comment by achannarasappa** [comment]
Thanks for the suggestion - I like the idea and feel that replacing the existing day change feature outright (without an option for day change) would be best. What are your thoughts?

**Comment by cpjolicoeur** [comment]
@achannarasappa That's your call as the owner.  I simply added the option to keep backwards compatibility with how it currently works, but if you'd prefer to just swap it completely I can make those changes as well.

**Comment by achannarasappa** [comment]
When making this decision, I'm considering which piece of information and provide the greatest value to users understanding the space is a hard constraint. Ideally we could make this decision based on data but this isn't possible in the case of ticker.

My hypothesis is that the total change in positions provides more value to users than day change because:
1. Percent day change will always equal the quote change which is present to the right and thus this information is redundant
2. Users have the ability to see their overall day change in their currency with `--show-summary`
3. Users derive comparatively less value from day value change

Based on these, I'd suggest making this a replacement to the existing day change without maintaining backwards compatibility. I'm still interested in hearing counter-points though to this idea but I don't that should hold up this change.

A feature that could be considered in the future would be an option to bring back the day value change on the same line as the total value right aligned with the total value change with an optional flag

**Comment by cpjolicoeur** [comment]
@achannarasappa I'm in a agreement with you.

To me, the default should be to show the totals, and that is why I forked an made this change.   As you pointed out, your new `--show-summary` option also now allows users to see the total day change as an aggregate across all lots.

I think it's reasonable, in the future, to expand the lot position display a bit if requested, to show the total (overall) change for the position and also show the day change for that specific lot.  There is enough space to do so and the display could easily handle it if needed.

I'll update my PR #61 to do as we discussed here and change the current implementation to show totals per lot vs daily change.  Also, this will remove the newly added configuration option, which is also a benefit in my eyes.

**Comment by cpjolicoeur** [comment]
@achannarasappa I've updated PR #61 per our discussion here.

**Comment by mjross** [comment]
I very much hope that this enhancement is made to the program, because the daily change would be useful only to someone who just happens to buy at the very beginning of that day, which must be a tiny fraction of use cases. Total change, on the other hand, would be extremely useful for short-term and long-term traders who want to sell a position once it is profitable.

**Comment by OscarHanzely** [comment]
Yes I agree, there is no point of displaying the total market value of the investment with the daily change trend. It basically shows investments that are up since inception but in red numbers because of daily downturn. Very confusing behavior. Plus one for this one.
